---
title: "Clinical Trial A5055"
date: "16 de mayo de 2022"
output:  
  pdf_document:
  toc_depth: 2
---
# Installation of required packages and functions.
```{r warning=FALSE, message=FALSE}


library(msm) 
library(ggplot2) 
library(tcltk)
library(numDeriv)
library(MASS)
library(base)
library(expm)
library(ARpLMEC)



```

# Reading and setting the dataset
```{r warning=FALSE,message=FALSE}
########################
# Dataset A5055        #
########################

data1 <- read.csv("dataA5055.csv")

attach(data1)
data1    <- subset(data1, !is.na(cd4))
subjects <- unique(data1$patid)
cluster  <- c(match(data1$patid,subjects))
m        <- length(subjects)
N        <- length(cluster)
y1       <- c(data1$logrna) 
y2.1     <- c(data1$cd4)
x        <- c(data1$day)
tem      <- c(data1$day)
treat    <- data1$arm 
nj       <- matrix(0,m,1)

for (j in 1:m){nj[j]=sum(cluster==j)}

cc                   <- (data1$rna<50)+0
y1[y1<=log10(50)]    <- log10(50)

##################################
# Excluding Subjects 4 and 8     #
##################################

for(i in c( 4,8))
{ y1[cluster==i]     = NA
y2.1[cluster==i]   = NA
x[cluster==i]      = NA
tem[cluster==i]    = NA
treat[cluster==i]  = NA
cc[cluster==i]     = NA
nj[i]              = NA
cluster[cluster==i]= NA }

y1      <- as.vector(na.omit(y1))
y2.1    <- as.vector(na.omit(y2.1))
x       <- as.vector(na.omit(x))
tem     <- as.vector(na.omit(tem))
treat   <- as.vector(na.omit(treat))
cc      <- as.vector(na.omit(cc))
nj      <- as.vector(na.omit(nj))
cluster <- as.vector(na.omit(cluster))

subjetos=unique(cluster)
for(i in 1:length(subjetos))
{
  cluster[cluster==subjetos[i]]=i
}

m <- length(nj)
N <- length(cluster)

#########################
# Design Matrix         #
#########################

xx1    <- cbind(rep(1,length(y1)),x,treat,y2.1^0.5,treat*x)
zz1    <- cbind(1,x)  
cc1    <- cc
nj1    <- nj
y1     <- y1
tempo1 <- tem

#######################
# Profiles Plot       #
#######################

datas   <- cbind(cluster,treat,x,y1,cc,y2.1)
nam_row <- as.character((1:312))
nam_col <- c("cluster","arm","day","logrna","cens","cd4")
datas   <- matrix(datas,nrow=312,ncol=6,
                  dimnames=list(" "=nam_row," "=nam_col))
dados   <- as.data.frame(datas)
attach(dados, warn.conflicts = FALSE)
dados2  <- dados

dados2$arm[dados2$arm=="1"] <- "treatment 1"
dados2$arm[dados2$arm=="2"] <- "treatment 2"

grafico <- ggplot(dados2, aes(x=day,y=logrna,group = cluster))
grafico + geom_line() +   geom_point(size = 2) + 
  labs(x = "Time (days)", y="log10 HIV-1 RNA") +
  facet_wrap(~ arm) +
  geom_hline(yintercept=log10(50),colour="red",linetype ="longdash")+
  theme_bw()

```

# Getting initial values from the UNC-N-LMEC model 
```{r warning=FALSE}
lm1.un1 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                        nj = nj1, struc = "UNC", typeModel = "Normal",
                        error = 0.00001, MaxIter = 10)

betasI  <- as.vector(lm1.un1$FixEffec$Est)
sigma2I <- lm1.un1$Sigma2$Est
alphasI <- diag(2)
LL1     <- rep(-Inf,length(y1))
LU1     <- as.vector(y1)

initial1 <- list(betas=betasI,sigma2=sigma2I,alphas=alphasI)

```

# Preliminary analysis
```{r warning=FALSE,results = 'hide'}
###########################################################
# Fit of the N-LMEC model without correlation structures  #
###########################################################
fitN     <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "UNC",initial = initial1,
                         typeModel = "Normal",LI=LL1,LS=LU1, error = 1e-4,
                         MaxIter = 500)

```

```{r warning=FALSE}
#################################################################
# Residuals of the N-LMEC model without correlation structures  #
#################################################################
res    <- fitY<-rep(0,length(y1))
efectob<- matrix(0,length(nj),2)
for (i in 1:length(nj)){ 
  efectob[i,] = fitN$others$ubi[(((i-1)*2)+1) : (i*2),i]
  resi        = fitN$others$yog[(sum(nj[1:i-1])+1) : (sum(nj[1:i]))]- 
  xx1[(sum(nj[1:i-1])+1) : (sum(nj[1:i])),]%*%fitN$FixEffect$Est
  res[(sum(nj[1:i-1])+1) : (sum(nj[1:i]))] = ((fitN$Sigma2$Est)^(-0.5))*resi
  fitY[(sum(nj[1:i-1])+1) : (sum(nj[1:i]))]= xx1[(sum(nj[1:i-1])+1):(sum(nj[1:i]))
                                                 ,]%*%fitN$FixEffect$Est+
                                  zz1[(sum(nj[1:i-1])+1):(sum(nj[1:i])),]%*%efectob[i,] 
}

plot(efectob[,1],efectob[,2],xlab=expression(Random~Effects~b[0]),
     ylab=expression(Random~Effects~b[1]) ,main = "(a)")
abline(h=0, lty=3)
plot(fitY,res,xlab= "Fitted values", ylab= "Residuals", main="(b)")
abline(h=0, lty=3, col=9)
qqnorm(efectob[,1], main = "(c)")
qqline(efectob[,1], lty=3)
qqnorm(efectob[,2], main = "(d)")
qqline(efectob[,2], lty=3)
qqnorm(res ,main = "(e)")
qqline(res , lty=3)

```

# Fit of the t-LMEC model under differents correlation structures
```{r warning=FALSE,results = 'hide'}
####################
# Initial values   #
####################

initial1 <- list(betas=betasI,sigma2=sigma2I,alphas=alphasI,nu=3)

#########################
# Fitted t-LMEC models  #
#########################


model1T1 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "UNC",initial = initial1 , 
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)
model1T2 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "DEC", initial = initial1,
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)
model1T3 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "DEC(AR)",initial = initial1,
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)
model1T4 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "SYM",initial = initial1, 
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)
model1T5 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "ARp", order = 1,initial = initial1, 
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)
model1T6 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "ARp", order = 2,initial = initial1, 
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)
model1T7 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "ARp", order = 3,initial = initial1, 
                         nu.fixed = FALSE, typeModel = "Student", error = 1e-4,
                         MaxIter = 500)

```
```{r warning=FALSE}
#########################
# Parameters estimates  #
#########################
Table1Betas  <- cbind(model1T1$FixEffect$Est,model1T2$FixEffect$Est,
                      model1T3$FixEffect$Est,model1T4$FixEffect$Est,
                      model1T5$FixEffect$Est,model1T6$FixEffect$Est,
                      model1T7$FixEffect$Est)
Table1sigmae <- cbind(model1T1$Sigma2$Est,model1T2$Sigma2$Est,
                      model1T3$Sigma2$Est,model1T4$Sigma2$Est,
                      model1T5$Sigma2$Est,model1T6$Sigma2$Est,
                      model1T7$Sigma2$Est)
Table1D      <- cbind(model1T1$RandEffect$Est,model1T2$RandEffect$Est,
                      model1T3$RandEffect$Est,model1T4$RandEffect$Est,
                      model1T5$RandEffect$Est,model1T6$RandEffect$Est,
                      model1T7$RandEffect$Est)
Table1Phi1   <- cbind(0,model1T2$Phi$Est[1],model1T3$Phi$Est,model1T4$Phi$Est,
                      model1T5$Phi$Est,model1T6$Phi$Est[1],model1T7$Phi$Est[1])
Table1Phi2   <- cbind(0,model1T2$Phi$Est[2],1,0,
                      0,model1T6$Phi$Est[2],model1T7$Phi$Est[2])
Table1Phi3   <- cbind(0,0,0,0,0,0,model1T7$Phi$Est[3])
Table1Nu     <- cbind(model1T1$nu,model1T2$nu,model1T3$nu,model1T4$nu,
                      model1T5$nu,model1T6$nu,model1T7$nu)

tableTlmec<-round(rbind(Table1Betas,Table1sigmae,Table1D,Table1Phi1,
                        Table1Phi2,Table1Phi3,Table1Nu),3)

colnames(tableTlmec)  <- c("UNC","DEC","DEC(AR)","SYM","AR(1)","AR(2)","AR(3)")
row.names(tableTlmec) <- c("beta0","beta1","beta2","beta3","beta4","sigma2",
                           "alpha11","alpha12","alpha22","phi1","phi2","phi3","nu")

print(tableTlmec)


####################
# Standard errors  #
####################

SET <- round(cbind(model1T1$FixEffect$SE,model1T2$FixEffect$SE,
                   model1T3$FixEffect$SE,model1T4$FixEffect$SE,
                   model1T5$FixEffect$SE,model1T6$FixEffect$SE,
                   model1T7$FixEffect$SE),3)

colnames(SET)  <- c("UNC","DEC","DEC(AR)","SYM","AR(1)","AR(2)","AR(3)")
row.names(SET) <- c("beta0","beta1","beta2","beta3","beta4")

print(SET)


##########################
# Information criterias  #
##########################

Table1AIC    <- cbind(model1T1$AIC,model1T2$AIC,model1T3$AIC,
                      model1T4$AIC,model1T5$AIC,model1T6$AIC,
                      model1T7$AIC)
Table1BIC    <- cbind(model1T1$BIC,model1T2$BIC,model1T3$BIC,
                      model1T4$BIC,model1T5$BIC,model1T6$BIC,
                      model1T7$BIC)
Table1loglik <- cbind(model1T1$loglik,model1T2$loglik,model1T3$loglik,
                      model1T4$loglik,model1T5$loglik,model1T6$loglik,
                      model1T7$loglik)

CriteriasT            <- rbind(Table1loglik,Table1AIC,Table1BIC)
colnames(CriteriasT)  <- c("UNC","DEC","DEC(AR)","SYM","AR(1)","AR(2)","AR(3)")
row.names(CriteriasT) <- c("loglik","AIC","BIC")

print(CriteriasT)

```

# Fit of the N-LMEC model under differents correlation structures
```{r warning=FALSE,results = 'hide'}
####################
# Initial values   #
####################

initial1 <- list(betas=betasI,sigma2=sigma2I,alphas=alphasI)

#########################
# Fitted N-LMEC models  #
#########################

model1N1 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "UNC", initial = initial1,
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)
model1N2 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "DEC",  initial = initial1,
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)
model1N3 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "DEC(AR)", initial = initial1,
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)
model1N4 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "SYM", initial = initial1,
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)
model1N5 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "ARp", order = 1, initial = initial1,
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)
model1N6 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "ARp", order = 2,  initial = initial1,
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)
model1N7 <- ARpMMEC.est(y = y1, x = xx1, z = zz1, tt = tempo1, cc = cc1,
                         nj = nj1, struc = "ARp", order = 3,  
                         typeModel = "Normal", error = 1e-4, MaxIter = 500)


```
```{r warning=FALSE}
#########################
# Parameters estimates  #
#########################

Table1Betas  <- cbind(model1N1$FixEffect$Est,model1N2$FixEffect$Est,
                      model1N3$FixEffect$Est,model1N4$FixEffect$Est,
                      model1N5$FixEffect$Est,model1N6$FixEffect$Est,
                      model1N7$FixEffect$Est)
Table1sigmae <- cbind(model1N1$Sigma2$Est,model1N2$Sigma2$Est,
                      model1N3$Sigma2$Est,model1N4$Sigma2$Est,
                      model1N5$Sigma2$Est,model1N6$Sigma2$Est,
                      model1N7$Sigma2$Est)
Table1D      <- cbind(model1N1$RandEffect$Est,model1N2$RandEffect$Est,
                      model1N3$RandEffect$Est,model1N4$RandEffect$Est,
                      model1N5$RandEffect$Est,model1N6$RandEffect$Est,
                      model1N7$RandEffect$Est)
Table1Phi1   <- cbind(0,model1N2$Phi$Est[1],model1N3$Phi$Est,model1N4$Phi$Est,
                      model1N5$Phi$Est,model1N6$Phi$Est[1],model1N7$Phi$Est[1])
Table1Phi2   <- cbind(0,model1N2$Phi$Est[2],1,0,
                      0,model1N6$Phi$Est[2],model1N7$Phi$Est[2])
Table1Phi3   <- cbind(0,0,0,0,0,0,model1N7$Phi$Est[3])

tableNlmec    <- round(rbind(Table1Betas,Table1sigmae,Table1D,Table1Phi1,
                             Table1Phi2,Table1Phi3),4)

colnames(tableNlmec)  <- c("UNC","DEC","DEC(AR)","SYM","AR(1)","AR(2)","AR(3)")
row.names(tableNlmec) <- c("beta0","beta1","beta2","beta3","beta4","sigma2",
                           "alpha11","alpha12","alpha22","phi1","phi2","phi3")

print(tableNlmec)

####################
# Standard errors  #
####################

SEN <- round(cbind(model1N1$FixEffect$SE,model1N2$FixEffect$SE,
                   model1N3$FixEffect$SE,model1N4$FixEffect$SE,
                   model1N5$FixEffect$SE,model1N6$FixEffect$SE,
                   model1N7$FixEffect$SE),4)

colnames(SEN)  <- c("UNC","DEC","DEC(AR)","SYM","AR(1)","AR(2)","AR(3)")
row.names(SEN) <- c("beta0","beta1","beta2","beta3","beta4")

print(SEN)

##########################
# Information criterias  #
##########################

Table1AIC1    <- cbind(model1N1$AIC,model1N2$AIC,model1N3$AIC,
                       model1N4$AIC,model1N5$AIC,model1N6$AIC,model1N7$AIC)
Table1BIC1    <- cbind(model1N1$BIC,model1N2$BIC,model1N3$BIC,
                       model1N4$BIC,model1N5$BIC,model1N6$BIC,model1N7$BIC)
Table1loglik1 <- cbind(model1N1$loglik,model1N2$loglik,model1N3$loglik,
                       model1N4$loglik,model1N5$loglik,model1N6$loglik,
                       model1N7$loglik)

CriteriasN           <- rbind(Table1loglik1,Table1AIC1,Table1BIC1)
colnames(CriteriasN)  <- c("UNC","DEC","DEC(AR)","SYM","AR(1)","AR(2)","AR(3)")
row.names(CriteriasN) <- c("loglik","AIC","BIC")

print(CriteriasN)

```

# Residual analysis of the DEC(AR)-t-LMEC model
```{r warning=FALSE}

obj     <- model1T3
efectob <- matrix(0,length(nj),2)
for (k in 1:length(nj)){ 
  efectob[k,] <- obj$others$ubi[(((k-1)*dim(zz1)[2])+1) : (k*dim(zz1)[2]), k]
}
plot(efectob[,1],efectob[,2],xlab=expression(Random~Effects~b[0]),
     ylab=expression(Random~Effects~b[1]) ,main = "(a)")
abline(h=0, lty=3)
plot(obj$Yfit,obj$Residual,xlab= "Fitted values", ylab= "Residuals",main = "(b)")
abline(h=0, lty=3, col=9)
qqnorm(efectob[,1], main = "(c)")
qqline(efectob[,1], lty=3)
qqnorm(efectob[,2],main = "(d)")
qqline(efectob[,2], lty=3)
qqnorm(obj$Residual,main = "(e)")
qqline(obj$Residual, lty=3)


```

